version: '3.7'

services:
  neo:
    image: neo4j:4.0.2
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - ./database/data:/data
      - ./database/logs:/logs
  quarkus:
    build:
      context: .
      dockerfile: ./Dockerfile.multistage
    ports:
      - 6789:6789
    environment:
      - NEO4J_URI=bolt://0.0.0.0:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=secret
