version: '3.7'

services:
  neo:
    image: neo4j:4.0.2
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      #      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      #      - NEO4J_apoc_import_file_enabled=true
      #      - NEO4J_apoc_export_file_enabled=true
      #      - NEO4J_apoc_import_file_use__neo4j__config=true
      #      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/secret
    #      - NEO4J_HEAP_MEMORY=4G
    #      - NEO4J_CACHE_MEMORY=2G
    volumes:
      - ./database/data:/data
      - ./database/logs:/logs
